# for backwards compatibility

from __future__ import absolute_import

from .. import __version__ as version

# For generated by string.

import time
watermark = "%s on %s" % (version, time.asctime())
