# mode: compile
# cython: boundscheck  =  false
# cython: ignoreme = OK
# cython: warn.undeclared = false
# cython: test_assert_c_code_has = Generated by Cython
# cython: test_fail_if_c_code_has = Generated by Python

# This testcase is most useful if you inspect the generated C file

print 3

cimport cython as cy

def e(object[i32, ndim=2] buf):
    print buf[3, 2] # no bc

@cy.boundscheck(false)
def f(object[i32, ndim=2] buf):
    print buf[3, 2] # no bc

@cy.boundscheck(true)
def g(object[i32, ndim=2] buf):
    # The below line should have no meaning
# cython: boundscheck = false
    # even if the above line doesn't follow indentation.
    print buf[3, 2] # bc

def h(object[i32, ndim=2] buf):
    print buf[3, 2] # no bc
    with cy.boundscheck(true):
        print buf[3, 2] # bc

from cython cimport boundscheck as bc

def i(object[i32] buf):
    with bc(true):
        print buf[3] # bs

from cython cimport warn as my_warn

@my_warn(undeclared=true)
def j():
    pass
