# mode: compile

# This caused a "maximum recursion depth exceeded" at some point,
# see https://github.com/cython/cython/issues/1744

cdef inline bint g(i32 x, i32 y): return True

cdef cython_bug(i32 u):
    try:
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
    finally:
        g(u, u)

cython_bug(1)
