name: Bug Report
description: File a bug report
title: "[BUG] "
body:
  - type: markdown
    attributes:
      value: |
        **PLEASE READ THIS FIRST:**
        - DO NOT use the bug and feature tracker for general questions and support requests.
        Use the [`cython-users`](https://groups.google.com/g/cython-users) mailing list instead.
        It has a wider audience, so you get more and better answers.
        - Did you search for SIMILAR ISSUES already?
        Please do, it helps to save us precious time that we otherwise could not invest into development.
        - Did you try the LATEST MASTER BRANCH or pre-release?
        It might already have what you want to report.
        Specifically, the legacy stable 0.29.x release series receives only important low-risk bug fixes.
        Also see the [Changelog](https://github.com/cython/cython/blob/master/CHANGES.rst) regarding recent changes
  - type: textarea
    id: describe
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Tell us what you see!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "Code to reproduce the behaviour:"
      value: |
        ```cython
        # example code
        ```
  - type: textarea
    id: expected
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
  - type: markdown
    attributes:
      value: |
        **Environment** - please complete the following information:
  - type: input
    id: environment_os
    attributes:
      label: "OS"
      placeholder: "e.g. Linux, Windows, macOS"
  - type: input
    id: environment_python_v
    attributes:
      label: "Python version"
      placeholder: "e.g. 3.10.2"
  - type: input
    id: environment_cython_v
    attributes:
      label: "Cython version"
      placeholder: "e.g. 3.0.0a11"
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

