blank_issues_enabled: false
contact_links:
  - name: I NEED HELP
    url: https://groups.google.com/g/cython-users
    about: Cython-users mailing list is a place to ask and answer support questions.
