name: CI

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      backend:
        required: true
        type: string
      extra_hash:
        required: false
        default:
        type: string
      limited_api:
        required: false
        default: ""
        type: string
      shared_utility:
        required: false
        default: ""
        type: string
      cython_compile_all:
        required: false
        default: "0"
        type: string
      no_cython_compile:
        required: false
        default: "0"
        type: string
      gcc_version:
        required: false
        default: "10"
        type: string
      extra_cflags:
        required: false
        default: ""
        type: string


permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-and-test:
    env:
      LIMITED_API: ${{ inputs.limited_api }}
      SHARED_UTILITY: ${{ inputs.shared_utility }}
      BACKEND: ${{ inputs.backend }}
      PYTHON_VERSION: ${{ inputs.python-version }}
      EXTRA_CFLAGS: ${{ inputs.extra_cflags }}
      CYTHON_COMPILE_ALL: ${{ inputs.cython_compile_all }}
      NO_CYTHON_COMPILE: ${{ inputs.no_cython_compile }}
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      GCC_VERSION: ${{ inputs.gcc_version }}
      USE_CCACHE: 1
      CCACHE_SLOPPINESS: "pch_defines,time_macros"
      CCACHE_COMPRESS: 1
      CCACHE_COMPRESSLEVEL: 5
      # Size guide: 10GB maximum cache storage / total number of CI jobs creating a cache.
      # However, a single run currently generates 170-210 MB, so less would use less but be useless.
      CCACHE_MAXSIZE: "220M"

    # This defaults to 360 minutes (6h) which is way too long and if a test gets stuck, it can block other pipelines.
    # From testing, the runs tend to take ~10-15 minutes for ubuntu / macos and ~25 for windows,
    # so a limit of 80 minutes should be enough. This can always be changed in the future if needed.
    timeout-minutes: ${{ startsWith(inputs.python-version, 'graalpy') && 150 || 80 }}
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Compilation Cache
        uses: hendrikmuhs/ccache-action@v1.2.20
        if: runner.os != 'Windows'  # There is currently no working sccache setup for Windows.
        with:
          variant: ${{ startsWith(runner.os, 'Windows') && 'sccache' || 'ccache' }}  # fake ternary
          create-symlink: ${{ startsWith(runner.os, 'Linux') && 'false' || 'true' }}  # fake ternary
          # Disable ccache saving from pull requests to reserve caching storage for the main branches.
          save: ${{ startsWith(github.ref, '/refs/pull/') && 'false' || 'true' }}  # fake ternary
          key: ${{ runner.os }}-${{ runner.arch }}-hendrikmuhs-ccache${{ inputs.extra_hash }}-${{ inputs.python-version }}-${{ inputs.backend == 'c' || inputs.backend == 'c,cpp' }}-${{ contains(inputs.backend, 'cpp') }}-${{ hashFiles('test-requirements*.txt', '.github/**/ci.yml', 'Tools/**/ci-run.sh') }}
          max-size: ${{ env.CCACHE_MAXSIZE }}

      - name: Run CI
        continue-on-error: false
        # Windows does not support job summary reports and has problems with pipes, so keep things simple there.
        run: |
          bash -c "\
            if [[ '${{runner.os}}' == 'Windows' ]]; then \
              bash ./Tools/ci-run.sh; \
            else \
              ${{runner.os == 'Linux' && 'stdbuf -e4M' || ''}}  bash ./Tools/ci-run.sh \
              2> >(tee  ${{runner.os == 'Linux' && '-p' || ''}} \
                >(tail -20 > ci-summary.txt) \
                >(grep -F ' SLOWTEST ' >ci-slowtests.txt) \
                >&2); \
            fi"

      - name: Report results
        if: runner.os != 'Windows'
        run: |
          bash -c "\
            if [[ -s ci-slowtests.txt ]]; then \
              echo '| Slow tests | duration |'; \
              echo '|:---|---:|'; \
              sed -e 's/^.*\[/|    / ; s/: SLOWTEST / | / ; s/\].*/ |/ ; s/_/\\\\_/g' ci-slowtests.txt | sort -nr -k4; \
              echo; \
            fi; \
            if [[ -s ci-summary.txt ]]; then \
              grep -A20 'Most expensive pipeline stages' ci-summary.txt | \
                sed -e '2,21s/^\(.*[^:]\)$/    \1/ ; s/^\(.*:\)$/\n\1\n/ ; 1,1s/: /:\n\n    / ; 1,1s/), /)\n    /g' ; \
            fi; \
            " >> $GITHUB_STEP_SUMMARY

      - name: Upload wheels
        uses: actions/upload-artifact@v6.0.0
        with:
          name: wheels-${{ runner.os }}-${{ runner.arch }}-${{ inputs.python-version }}${{ inputs.extra_hash }}
          path: dist/*.whl
          if-no-files-found: ignore
