name: CI

on:
  push:
    paths:
      - '**'
      - '!Demos/benchmarks/**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**'
      - '!Demos/benchmarks/**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  MACOSX_DEPLOYMENT_TARGET: "11.0"
  GCC_VERSION: 10
  USE_CCACHE: 1
  CCACHE_SLOPPINESS: "pch_defines,time_macros"
  CCACHE_COMPRESS: 1
  CCACHE_COMPRESSLEVEL: 5
  # Size guide: 10GB maximum cache storage / total number of CI jobs creating a cache.
  # However, a single run currently generates 170-210 MB, so less would use less but be useless.
  CCACHE_MAXSIZE: "220M"


jobs:

  ci-early:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-latest]
        backend: [c, cpp]

        include:
          # Limited API
          - os: ubuntu-22.04
            backend: "c,cpp"
            limited_api: "--limited-api --abi3audit"
            extra_hash: "-limited_api"
          # Cython Shared Module
          - os: ubuntu-22.04
            backend: "c,cpp"
            shared_utility: "--shared-utility"
            extra_hash: "--shared-utility"

    uses: ./.github/workflows/ci-job.yml
    with:
      python-version: "3.14"
      os: ${{ matrix.os }}
      backend: ${{ matrix.backend }}
      limited_api: ${{ matrix.limited_api }}
      shared_utility: ${{ matrix.shared_utility }}
      extra_hash: ${{ matrix.extra_hash }}


  ci-all:
    needs: [codespell, codestyle, ci-early, build_docs]

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false

      # MATRIX:
      # =======
      # Required parameters:
      #  os                  the os to run on
      #  python-version      the python version to use
      #  backend             the backend to use
      # Optional parameters:
      #  limited_api         extra flags related to the limited api
      #  shared_utility      extra flags relating to the shared utility
      #  gcc_version
      #  extra_cflags
      #  cython_compile_all  '1' to build cython with "compile all"
      #  no_cython_compile   '1' to not compile cython itself
      #  extra_hash          extra hash str to differentiate from other caches with similar name (must always start with '-')
      matrix:
        # Tests [amd64]
        #
        os: [ubuntu-22.04, windows-2022, macos-latest]
        backend: [c, cpp]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.13t"
          #- "3.14"  # ci-early
          - "3.14t"
          - "3.15-dev"
          - "3.15t-dev"

        exclude:
          # Windows and free-threading is difficult to build right now
          - os: windows-2022
            python-version: 3.13t
            backend: "c"
          - os: windows-2022
            python-version: 3.13t
            backend: "cpp"
          - os: windows-2022
            python-version: 3.14t
            backend: "c"
          - os: windows-2022
            python-version: 3.14t
            backend: "cpp"

        include:
          # Ubuntu sub-jobs:
          # ================
          # GCC 13 (with broad language standards)
          - os: ubuntu-22.04
            python-version: "3.9"
            backend: c
            gcc_version: 13
            extra_cflags: "-std=c99"
            extra_hash: "-c99"
          - os: ubuntu-22.04
            python-version: "3.10"
            backend: c
            gcc_version: 13
            extra_cflags: "-std=c17"
            extra_hash: "-c17"
          - os: ubuntu-22.04
            python-version: "3.12"
            backend: c
            gcc_version: 13
            extra_cflags: "-std=c17"
            extra_hash: "-c17"
          - os: ubuntu-22.04
            python-version: "3.13"
            backend: cpp
            gcc_version: 13
            extra_cflags: "-std=c++20"
            extra_hash: "-cpp20"
          # Arm64
          - os: ubuntu-22.04-arm
            python-version: "3.13"
            backend: c
          - os: ubuntu-22.04-arm
            python-version: "3.13"
            backend: cpp
          - os:  windows-11-arm
            python-version: "3.13"
            backend: "c"
          - os:  windows-11-arm
            python-version: "3.13"
            backend: "cpp"
          # compile all modules
          - os: ubuntu-22.04
            python-version: "3.9"
            backend: c
            cython_compile_all: 1
            extra_hash: "-all"
          - os: ubuntu-22.04
            python-version: "3.9"
            backend: cpp
            cython_compile_all: 1
            extra_hash: "-all"
          - os: ubuntu-22.04
            python-version: "3.11"
            backend: c
            cython_compile_all: 1
            extra_hash: "-all"
          - os: ubuntu-22.04
            python-version: "3.11"
            backend: cpp
            cython_compile_all: 1
            extra_hash: "-all"
          # Limited API
          - os: ubuntu-22.04
            python-version: "3.9"
            backend: "c,cpp"
            limited_api: "--limited-api --abi3audit"
            extra_hash: "-limited_api"
          - os: ubuntu-22.04
            python-version: "3.11"
            backend: "c,cpp"
            limited_api: "--limited-api --abi3audit"
            extra_hash: "-limited_api"
          - os: ubuntu-22.04
            python-version: "3.12"
            backend: "c,cpp"
            limited_api: "--limited-api --abi3audit"
            extra_hash: "-limited_api"
          - os: ubuntu-22.04
            python-version: "3.15-dev"
            backend: "c,cpp"
            limited_api: "--limited-api"
            extra_hash: "-limited_api"
          # Cython Shared Module
          - os: ubuntu-22.04
            python-version: "3.12"
            backend: "c,cpp"
            shared_utility: "--shared-utility"
            extra_hash: "--shared-utility"
          # Type specs
          - os: ubuntu-22.04
            python-version: "3.14"
            backend: c
            extra_cflags: "-DCYTHON_USE_TYPE_SPECS=1"
            extra_hash: "-typespecs"
          - os: ubuntu-22.04
            python-version: "3.12"
            backend: c
            extra_cflags: "-DCYTHON_USE_TYPE_SPECS=1"
            extra_hash: "-typespecs"
          - os: ubuntu-22.04
            python-version: "3.9"
            backend: c
            extra_cflags: "-DCYTHON_USE_TYPE_SPECS=1"
            extra_hash: "-typespecs"
          # Pypy
          - os: ubuntu-22.04
            python-version: pypy-3.9
            backend: c
            no_cython_compile: 1
          - os: ubuntu-22.04
            python-version: pypy-3.10
            backend: c
            no_cython_compile: 1
          - os: ubuntu-22.04
            python-version: pypy-3.11
            backend: c
            no_cython_compile: 1
          # GraalPy
          - os: ubuntu-22.04
            python-version: graalpy25
            backend: c
            no_cython_compile: 1

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ matrix.backend }}
      extra_hash: ${{ matrix.extra_hash }}


  ci-success:
    needs: ci-all
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: true


  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Codespell
        uses: codespell-project/actions-codespell@v2


  codestyle:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      PYTHON_VERSION: "3.13"
      BACKEND: "c,cpp"
      TEST_CODE_STYLE: "1"
      NO_CYTHON_COMPILE: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run codestyle
        run: |
          bash -c "\
            python -m pip install --no-cache-dir -U pip || exit 1 ; \
            python -m pip install --no-cache-dir -r test-requirements.txt || exit 1 ; \
            python runcodestyle.py \
              2> >(tee >(egrep '.+:[0-9]+: ' | sed -e 's/^/    /' >> $GITHUB_STEP_SUMMARY) >&2) \
            "

  build_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      PYTHON_VERSION: "3.13"
      BACKEND: "c,cpp"
      TEST_CODE_STYLE: "1"
      NO_CYTHON_COMPILE: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build HTML docs
        run: |
          python -m pip install --no-cache-dir -r doc-requirements.txt
          make -C docs html

      - name: Upload HTML docs
        uses: actions/upload-artifact@v6.0.0
        with:
          name: htmldocs
          path: docs/build/html
          if-no-files-found: ignore
