name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  MACOSX_DEPLOYMENT_TARGET: "11.0"
  GCC_VERSION: 10
  USE_CCACHE: 1
  CCACHE_SLOPPINESS: "pch_defines,time_macros"
  CCACHE_COMPRESS: 1
  CCACHE_COMPRESSLEVEL: 5
  # Size guide: 10GB maximum cache storage / total number of CI jobs creating a cache.
  # However, a single run currently generates 170-210 MB, so less would use less but be useless.
  CCACHE_MAXSIZE: "220M"


jobs:
  file-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      ci-changes: ${{ steps.filter.outputs.any-files == 'true' && (steps.filter.outputs.negative-files == 'false' || steps.filter.outputs.positive-github == 'true') && (steps.filter.outputs.negative-docs == 'false' || steps.filter.outputs.positive-docs == 'true') }}
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
      # Only needed to compare the "base" on push; not needed for PR
      if: ${{ github.event_name == 'push' }}
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d  # v4.0.1
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          any-files:
          - '**'
          negative-files:
          - 'Demos/benchmarks/**'
          - '.github/**'
          positive-github:
          - '.github/workflows/ci*.yml'
          negative-docs:
          - '**/*.md'
          - '**/*.rst'
          - 'docs/**'
          positive-docs:
          - 'docs/examples/**'

  ci-early:
    needs: [file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}
    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, windows-2022, macos-latest]
        backend: [c, cpp]
        limited_api: ['']
        shared_utility: ['']
        extra_hash: ['']

        include:
          # Limited API
          - os: ubuntu-24.04
            backend: "c"
            limited_api: true
            abi3audit: true
            extra_hash: "-limited_api"
          - os: ubuntu-24.04
            backend: "cpp"
            limited_api: true
            abi3audit: true
            extra_hash: "-limited_api"
          # Cython Shared Module
          - os: ubuntu-24.04
            backend: "c"
            shared_utility: "--shared-utility"
            extra_hash: "-shared-utility"
          - os: ubuntu-24.04
            backend: "cpp"
            shared_utility: "--shared-utility"
            extra_hash: "-shared-utility"

    uses: ./.github/workflows/ci-job.yml
    with:
      python-version: "3.14"
      os: ${{ matrix.os }}
      backend: ${{ matrix.backend }}
      limited_api: ${{ matrix.limited_api }}
      abi3audit: ${{ matrix.abi3audit }}
      shared_utility: ${{ matrix.shared_utility }}
      extra_hash: ${{ matrix.extra_hash }}
      upload_testsources: ${{ startsWith(matrix.os, 'ubuntu') }}


  ci-early-success:
    needs: [codespell, codestyle, ci-early, build_docs]
    if: always()
    env:
      FAIL: ${{ case(contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'), 1, 0) }}
    runs-on: ubuntu-latest
    steps:
      - run: exit $FAIL


  ci-all:
    needs: [ci-early-success, file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false

      # MATRIX:
      # =======
      # Required parameters:
      #  os                  the os to run on
      #  python-version      the python version to use
      #  backend             the backend to use
      # Optional parameters:
      #  limited_api         bool for use limited api
      #  abi3audit           bool for use abi3audit
      #  shared_utility      extra flags relating to the shared utility
      #  gcc_version
      #  extra_cflags
      #  cython_compile_all  '1' to build cython with "compile all"
      #  no_cython_compile   '1' to not compile cython itself
      #  extra_hash          extra hash str to differentiate from other caches with similar name (must always start with '-')
      matrix:
        # Tests [amd64]
        #
        os: [ubuntu-24.04, windows-2022, macos-latest]
        backend: [c, cpp]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.13t"
          #- "3.14"  # -> 'ci-early'
          - "3.14t"
          - "3.15-dev"
          - "3.15t-dev"

        exclude:
          # Windows and free-threading is difficult to build right now
          - os: windows-2022
            python-version: 3.13t
            backend: "c"
          - os: windows-2022
            python-version: 3.13t
            backend: "cpp"
          - os: windows-2022
            python-version: 3.14t
            backend: "c"
          - os: windows-2022
            python-version: 3.14t
            backend: "cpp"

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ matrix.backend }}


  ci-arm64:
    # ARM builds
    needs: [ci-early-success, file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, windows-11-arm]
        backend: [c, cpp]
        python-version:
          - "3.x"  # latest

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ matrix.backend }}


  ci-typespecs:
    # compile with typespecs
    needs: [ci-early-success, file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.12"
          - "3.14"
        backend: [c]
        os: [ubuntu-24.04]

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ matrix.backend }}
      extra_cflags: "-DCYTHON_USE_TYPE_SPECS=1"
      extra_hash: "-typespecs"


  ci-sharedmodule:
    # compile with shared utility module
    needs: [ci-early-success, file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        backend: [c,cpp]
        python-version:
          - "3.12"
          #- "3.14"  # -> 'ci-early'
        os: [ubuntu-24.04]

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ matrix.backend }}
      shared_utility: "--shared-utility"
      extra_hash: "-shared-utility"


  ci-compileall:
    # compile all modules
    needs: [ci-early-success, file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        backend: [c, cpp]
        python-version:
          - "3.9"
          - "3.11"
        os: [ubuntu-24.04]

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ matrix.backend }}
      cython_compile_all: "1"
      extra_hash: "-all"


  ci-stdc:
    # GCC/clang with broad language standards
    needs: [ci-early-success, file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        cstd: ['c99']
        python-version: ['3.9']
        os: [ubuntu-24.04]

        include:
          - cstd: "c99"
            python-version: "3.9"
            os: ubuntu-24.04  # GCC
          - cstd: "c99"
            python-version: "3.9"
            os: macos-latest  # clang
          - cstd: "c17"
            python-version: "3.10"
            os: ubuntu-24.04  # GCC
          - cstd: "c17"
            python-version: "3.12"
            os: ubuntu-24.04  # GCC
          - cstd: "c17"
            os: macos-latest  # clang
            python-version: "3.12"
          - cstd: "c2x"  # "c23"
            python-version: "3.12"
            os: ubuntu-24.04  # GCC
          - cstd: "c++20"
            python-version: "3.13"
            os: ubuntu-24.04  # GCC

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ startsWith(matrix.cstd, 'cpp') && 'cpp' || 'c' }}
      extra_cflags: "-std=${{ matrix.cstd }}"
      extra_hash: "-${{ matrix.cstd == 'c++20' && 'cpp20' || matrix.cstd }}"
      gcc_version: "13"


  ci-lapi:
    # Limited API tests
    needs: [ci-early-success, file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          #- "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          #- "3.13t"
          #- "3.14"  # -> 'ci-early'
          #- "3.14t"
          - "3.15-dev"
          #- "3.15t-dev"
        os: [ubuntu-24.04]
        backend: [c, cpp]

        include:
          - os: macos-latest
            python-version: "3.14"
            backend: c
          - os: macos-latest
            python-version: "3.14"
            backend: cpp

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ matrix.backend }}
      limited_api: true
      abi3audit: ${{ !endsWith(matrix.python-version, '-dev') }}
      extra_hash: "-limited_api"
      # skip 3.10 because it somehow ends up deleting most of the .so files
      extra_python_versions: |-
        ${{ case(
          matrix.python-version == '3.9', '3.11 3.12 3.13 3.14 ',
          matrix.python-version == '3.11', '3.12 3.13 3.14',
          matrix.python-version == '3.12', '3.13 3.14',
          matrix.python-version == '3.13', '3.14',
          '') }}


  ci-noncpython:
    # PyPy, GraalPython, ...
    needs: [ci-early-success, file-changes]
    if: ${{ github.event_name == 'workflow_dispatch' || needs.file-changes.outputs.ci-changes == 'true' }}

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        python-version:
          - pypy-3.9
          - pypy-3.10
          - pypy-3.11-v7.3.21  # TODO remove pin when https://github.com/pypy/pypy/issues/5472 is fixed in a release
          - graalpy25
        os: [ubuntu-24.04]
        backend: [c]

    uses: ./.github/workflows/ci-job.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      backend: ${{ matrix.backend }}
      no_cython_compile: "1"


  ci-success:
    needs: [ci-early-success, ci-all, ci-arm64, ci-typespecs, ci-sharedmodule, ci-compileall, ci-stdc, ci-lapi, ci-noncpython]
    if: always()
    env:
      FAIL: ${{ case(contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'), 1, 0) }}
    runs-on: ubuntu-latest
    steps:
      - run: exit $FAIL


  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Codespell
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2


  codestyle:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      PYTHON_VERSION: "3.13"

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run codestyle
        run: |
          bash -c "\
            python -m pip install --no-cache-dir -U pip || exit 1 ; \
            python -m pip install --no-cache-dir -r test-requirements.txt || exit 1 ; \
            python runcodestyle.py \
              2> >(tee >(egrep '.+:[0-9]+: ' | sed -e 's/^/    /' >> $GITHUB_STEP_SUMMARY) >&2) \
            "

  build_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      PYTHON_VERSION: "3.13"

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build HTML docs
        run: |
          python -m pip install --no-cache-dir -r doc-requirements.txt
          make -C docs html

      - name: Upload HTML docs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: htmldocs
          path: docs/build/html
          if-no-files-found: ignore
