name: Sanitizers

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  label:
    # Accepted labels (in the 'if' condition below) are:
    # * sanitizers
    # * full_sanitizers - runs thread sanitizer on all tests
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  file-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs: ci-changes: ${{ steps.filter.outputs.files }}
    steps:
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d  # v4.0.1
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          push-files:
          - ".github/workflows/sanitizers.yml"
          - ".github/workflows/compiled_python.yml"
          - "Cython/**"
          - "tests/**"
          pr-files:
          - ".github/workflows/sanitizers.yml"
          - ".github/workflows/compiled_python.yml"
          - "Cython/Utility/**"
          - "Cython/Compiler/Nodes.py"
          - "Cython/Compiler/ExprNodes.py"
          - "Cython/Compiler/Optimize.py"

  sanitizers:
    needs: [file-changes]
    strategy:
      fail-fast: false
      matrix:
        # TODO memory sanitizer would be nice (but is hard)
        sanitizer: ["address,undefined", "thread", "thread,ft"]
    uses: ./.github/workflows/compiled_python.yml
    with:
      compiler: clang
      cpp_compiler: clang++
      sanitize: ${{ matrix.sanitizer }}
      name: ${{ matrix.sanitizer }}
    if: ${{ case(github.event_name == 'push', needs.file-changes.outputs.push-files == 'true', github.event_name == 'pull_request', needs.file-changes.outputs.pr-files == 'true', github.event_name == 'label', github.event.label.name == 'sanitizers' || github.event.label.name == 'full_sanitizers', 'true') }}

  pydebug:
    uses: ./.github/workflows/compiled_python.yml
    with:
      name: pydebug
    needs: [file-changes]
    if: ${{ case(github.event_name == 'push', needs.file-changes.outputs.push-files == 'true', github.event_name == 'pull_request', needs.file-changes.outputs.pr-files == 'true', 'true') }}
